version: "3.8"

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: atcantarctic
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - antarctic-app
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "dotnet publish -c Release -o ./publish && dotnet ./publish/AtcAntarctic.dll"
networks:
  antarctic-app:
    external: true
#    driver: bridge

#  nginx-dotnet:
#    image: nginx:alpine
#    container_name: nginx-dotnet
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "80:80"
#    networks:
#      - app-network
#    depends_on:
#      - app   
#networks:
#  app-network:
#    driver: bridge