version: "3.8"

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: atcantarctic
    ports:
      - "5174:5174"
    networks:
      - app-network
    volumes:
      - .:/app
    working_dir: /app
#    command: dotnet exec bin/Debug/net6.0/publish/AtcAntarctic.dll
  #    command: dotnet publish
#    dotnet exec bin/Debug/net6.0/publish/AtcAntarctic.dll  
    command: dotnet run
#    command: dotnet watch run
  
  nginx-dotnet:
    image: nginx:alpine
    container_name: nginx-dotnet
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app   
networks:
  app-network:
    driver: bridge